/// Writes the showcase site's copy of the brand mark and signature.
///
/// GitHub Pages publishes `site/` and nothing above it, so the site cannot
/// point at the app's own assets. The mark is the one thing worth carrying
/// across: it is what the page has instead of a logo, and the icon master is
/// a raster with the room the OS mask needs baked into it — at the header's
/// size that padding is most of the picture, and the edges soften at every
/// size but one.
///
/// So the SVG is drawn from the same outlines the app draws,
/// `PatraLogoPaths.leaf1` and `leaf2`, and the same gold, `patraAccent` in
/// `lib/src/theme.dart`. Neither is retyped: this is the seam, and re-running
/// it after the kit is re-exported is the whole of what regenerating means.
///
///   dart run tool/gen_web_mark.dart
///
/// It writes three files: the mark, the signature, and **the signature in
/// ink** — the one the store's feature graphic wears, because that asset is
/// drawn on ivory rather than on the night blue every other surface of ours
/// is, and an `<img>` cannot be told its colour by the page around it.
///
/// The two leaves are flattened from `Path()` calls, which is all the paths
/// file contains — `dart:ui` is not reachable from a plain `dart run`, so the
/// commands are read rather than executed. Bounds are computed exactly (a
/// quadratic's extrema have a closed form) rather than sampled, because the
/// viewBox is what stops the shirorekha being clipped.
library;

import 'dart:io';
import 'dart:math' as math;

const _outPath = 'site/assets/img/patra-mark.svg';
const _outPathSig = 'site/assets/img/patra-signature.svg';
const _outPathSigInk = 'store/patra-signature-ink.svg';
const _pathsFile = 'lib/src/branding/patra_logo_paths.dart';
const _signatureFile = 'lib/src/branding/patra_signature.dart';
const _themeFile = 'lib/src/theme.dart';

/// The two halves of the word, in the order the mark paints them.
const _leaves = ['leaf1', 'leaf2'];

void main() {
  final source = File(_pathsFile).readAsStringSync();
  final theme = File(_themeFile).readAsStringSync();
  final accent = _colour(theme, 'patraAccent');

  // Read the kit constants from the paths file.
  final wordmarkWidth = _readConstant(source, 'wordmarkWidth');

  // And the signature's own geometry from the one place that draws it, so the
  // period cannot come out in a different place here than in the app.
  final signature = File(_signatureFile).readAsStringSync();
  final dotRadius = _readConstant(signature, '_dotRadius');
  final dotGap = _readConstant(signature, '_dotGap');
  final baseline = _readConstant(signature, '_baseline');

  final d = StringBuffer();
  final bounds = _Bounds();
  for (final leaf in _leaves) {
    _flatten(_leaf(source, leaf), d, bounds);
  }

  final box = bounds.padded();
  final width = _n(box.right - box.left, 3);
  final height = _n(box.bottom - box.top, 3);
  final svg =
      '''
<!-- Generated by tool/gen_web_mark.dart from lib/src/branding/patra_logo_paths.dart.
     Do not hand-edit: run the tool again. The fill is patraAccent (lib/src/theme.dart). -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${_n(box.left, 3)} ${_n(box.top, 3)} $width $height" width="$width" height="$height" role="img" fill="$accent">
  <title>Patra</title>
  <path d="$d"/>
</svg>
''';

  File(_outPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(svg);
  stdout.writeln('Wrote $_outPath — $width x $height, $accent.');

  // --- Signature: wordmark + period ---
  final dotCentreX = wordmarkWidth + dotGap + dotRadius;
  final dotCentreY = baseline - dotRadius;

  final sigSource = _leaf(source, 'wordmark');
  final sigD = StringBuffer();
  final sigBounds = _Bounds();
  _flatten(sigSource, sigD, sigBounds);

  // The signature bounds: wordmark bounds expanded to include period
  final sigBox = (
    left: sigBounds._left,
    top: sigBounds._top,
    right: math.max(sigBounds._right, dotCentreX + dotRadius),
    bottom: math.max(sigBounds._bottom, dotCentreY + dotRadius),
  );
  final sigWidthOut = _n(sigBox.right - sigBox.left, 3);
  final sigHeightOut = _n(sigBox.bottom - sigBox.top, 3);

  // The wordmark path (without period) is in sigD. The period is a separate circle.
  final wordD = sigD.toString().trim();

  // Two of them, and the colour of the word is the whole difference: the
  // signature is ivory on the night blue every surface of ours is, and ink on
  // the one page that is not — Play's feature graphic, which is drawn on
  // ivory because Google refuses a dark field. An `<img>` cannot be told
  // either colour by the page around it, so the file says it.
  for (final (path, word) in [
    (_outPathSig, _colour(theme, 'patraText')),
    (_outPathSigInk, _colour(theme, 'patraBg')),
  ]) {
    final sigSvg =
        '''
<!-- Generated by tool/gen_web_mark.dart from lib/src/branding/patra_logo_paths.dart.
     Do not hand-edit: run the tool again. The word is $word, the dot is $accent. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${_n(sigBox.left, 3)} ${_n(sigBox.top, 3)} $sigWidthOut $sigHeightOut" width="$sigWidthOut" height="$sigHeightOut" role="img">
  <title>Patra</title>
  <g fill="$word">
    <path d="$wordD"/>
  </g>
  <circle cx="${_n(dotCentreX, 3)}" cy="${_n(dotCentreY, 3)}" r="${_n(dotRadius, 3)}" fill="$accent"/>
</svg>
''';
    File(path)
      ..createSync(recursive: true)
      ..writeAsStringSync(sigSvg);
    stdout.writeln('Wrote $path — $sigWidthOut x $sigHeightOut, $word.');
  }
}

/// Reads a constant double from the paths file, `static` or not.
double _readConstant(String source, String name) {
  final pattern = RegExp('\\s*(?:static )?const $name\\s*=\\s*([\\d.]+);');
  final match = pattern.firstMatch(source);
  if (match == null) throw StateError('$name is not in $_pathsFile.');
  return double.parse(match.group(1)!);
}

/// The commands of one leaf, joined into a single `d`.
///
/// One element rather than two: nothing on the page needs to address the
/// halves apart, and the app only splits them because the launch animation
/// drifts one in from each side.
void _flatten(String block, StringBuffer d, _Bounds bounds) {
  final command = RegExp(r'(moveTo|lineTo|quadraticBezierTo|close)\(([^)]*)\)');
  var x = 0.0;
  var y = 0.0;
  var found = 0;
  for (final match in command.allMatches(block)) {
    final kind = match.group(1)!;
    // `close()` takes no arguments; splitting its empty group would throw.
    final args = kind == 'close'
        ? const <double>[]
        : match
              .group(2)!
              .split(',')
              .map((a) => double.parse(a.trim()))
              .toList();
    switch (kind) {
      case 'moveTo':
        x = args[0];
        y = args[1];
        d.write('M ${_n(x, 2)} ${_n(y, 2)} ');
        bounds.add(x, y);
        found++;
      case 'lineTo':
        x = args[0];
        y = args[1];
        d.write('L ${_n(x, 2)} ${_n(y, 2)} ');
        bounds.add(x, y);
        found++;
      case 'quadraticBezierTo':
        final cx = args[0];
        final cy = args[1];
        final ex = args[2];
        final ey = args[3];
        d.write('Q ${_n(cx, 2)} ${_n(cy, 2)} ${_n(ex, 2)} ${_n(ey, 2)} ');
        bounds.addQuadratic((x, y), (cx, cy), (ex, ey));
        x = ex;
        y = ey;
        found++;
      case 'close':
        d.write('Z ');
    }
  }
  if (found == 0) throw StateError('No path commands found in the block.');
}

/// The `Path()` initialiser of one leaf, up to the next declaration.
String _leaf(String source, String name) {
  final marker = 'static final $name = Path()';
  final start = source.indexOf(marker);
  if (start < 0) throw StateError('$name is not in $_pathsFile.');
  final end = source.indexOf('static final', start + marker.length);
  return source.substring(start, end < 0 ? source.length : end);
}

/// A token of `theme.dart` as the site should carry it.
///
/// Read rather than copied: a gold that moved in the app and not here would
/// be the mark coming out a different colour from the word beside it, which
/// is the one thing on the page that is unmistakably wrong.
String _colour(String theme, String name) {
  final match = RegExp('const $name = Color\\(0x([0-9A-Fa-f]{8})\\)')
      .firstMatch(theme);
  if (match == null) throw StateError('$name is not in $_themeFile.');
  final argb = int.parse(match.group(1)!, radix: 16);
  return '#${(argb & 0xFFFFFF).toRadixString(16).padLeft(6, '0').toUpperCase()}';
}

/// A number as short as it can be written without losing what it means.
String _n(double value, int decimals) {
  final fixed = value.toStringAsFixed(decimals);
  return fixed.contains('.')
      ? fixed.replaceFirst(RegExp(r'\.?0+$'), '')
      : fixed;
}

typedef _Point = (double, double);

/// The extent of the two leaves together.
class _Bounds {
  double _left = double.infinity;
  double _top = double.infinity;
  double _right = double.negativeInfinity;
  double _bottom = double.negativeInfinity;

  void add(double x, double y) {
    _left = math.min(_left, x);
    _top = math.min(_top, y);
    _right = math.max(_right, x);
    _bottom = math.max(_bottom, y);
  }

  /// A curve reaches past both its endpoints wherever it turns, so its
  /// extrema are added too — solved, not sampled, so the box is the shape's
  /// and not an approximation that clips the top of the shirorekha.
  void addQuadratic(_Point p0, _Point control, _Point p1) {
    add(p0.$1, p0.$2);
    add(p1.$1, p1.$2);
    for (final t in [
      _extremum(p0.$1, control.$1, p1.$1),
      _extremum(p0.$2, control.$2, p1.$2),
    ]) {
      // Written so that a NaN — a curve whose denominator is zero — fails
      // the test rather than passing a pair of `false` comparisons.
      if (!(t > 0 && t < 1)) continue;
      final u = 1 - t;
      final x = u * u * p0.$1 + 2 * u * t * control.$1 + t * t * p1.$1;
      final y = u * u * p0.$2 + 2 * u * t * control.$2 + t * t * p1.$2;
      add(x, y);
    }
  }

  /// Where a quadratic turns on one axis: `(p0 - c) / (p0 - 2c + p1)`.
  double _extremum(double p0, double c, double p1) {
    final denominator = p0 - 2 * c + p1;
    return denominator == 0 ? double.nan : (p0 - c) / denominator;
  }

  /// The extent, rounded outwards: a viewBox a hair too tight shaves the
  /// shape, and one a hair too wide is invisible.
  ({double left, double top, double right, double bottom}) padded() => (
    left: (_left * 1000).floorToDouble() / 1000,
    top: (_top * 1000).floorToDouble() / 1000,
    right: (_right * 1000).ceilToDouble() / 1000,
    bottom: (_bottom * 1000).ceilToDouble() / 1000,
  );
}